version: '3.1'
services:
  db:
    image: mysql:5.7.21
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      service_network:
volumes:
  data:

networks:
  service_network:
