services:
  api:
    image: 'alta0815/assetsfirst-api:latest'
    container_name: trade
    ports:
      - "3000:8080"
    mem_limit: 1g
    env_file: .env
    restart: 'always'
    networks:
      - 'net'

networks:
  net:
