export enum CardContainerType {
  ALLOCATION = 'ALLOCATION',
  DIVIDEND_INCOME = 'DIVIDEND_INCOME',
  DIVIDEND_GOALS = 'DIVIDEND_GOALS',
  SECTORAL_DISTRIBUTION = 'SECTORAL_DISTRIBUTION',
  BALANCE = 'BALANCE',
  CONTRIBUTION = 'CONTRIBUTION',
  INVESTMENT_YIELD = 'INVESTMENT_YIELD',
  EQUITY_RISK_PREMIUM = 'EQUITY_RISK_PREMIUM',
  ASSET_DISPOSAL = 'ASSET_DISPOSAL',
}
