export enum CardContainerType {
  ALLOCATION = 'ALLOCATION',
  DIVIDENDS = 'DIVIDENDS',
  DIVIDEND_GOALS = 'DIVIDEND_GOALS',
  SECTORAL_DISTRIBUTION = 'SECTORAL_DISTRIBUTION',
  BALANCE = 'BALANCE'
}
